### ISSUE TITLE
Fails to load with on server

### ISSUE THREAD

**Issue by RuhaiHu** [RootsTeam/AdventureBags#1]
Looks like it's having some issue with a proxy while the server is loading it.
http://pastebin.com/8ueKjZuV

**Comment by ShadowGamerXY** [comment]
i am on vacation right now so i cant post the fic because my laptop doesnt have an internet connection but i will look into it and post a fix as soon as i get an internet connection

**Comment by ShadowGamerXY** [comment]
found the problem fixed it now works fine. Hopr you have a great day.

**Comment by Claycorp** [comment]
This issue isn't fixed in 0.3.0
http://pastebin.com/MHsgWLHs

If you have a fixed version please upload it to curse.

**Comment by ShadowGamerXY** [comment]
Will do I did not upload the 0.4 version yet because i need to implement a few things

**Comment by Ravin890** [comment]
Lol me and shadow had realized this a ittle time back and he fixed it then. (I have usable file but will wait for him to upload it)
