### ISSUE TITLE
When the inventory is full, the game crashes

### ISSUE THREAD

**Issue by MarkAgus** [RootsTeam/AdventureBags#9]
When the inventory is full, the game will crash. When I use the Shift key to move objects quickly from the backpack to the inventory being full, the game stops working. I do not know why this happens but I guess it has an easy solution. It happened to me in 1.12.2
Here is the crash file
[crash-2018-07-04_01.06.34-client.txt](https://github.com/ShadowGamerXY/AdventureBags/files/2161350/crash-2018-07-04_01.06.34-client.txt)

**Comment by ShadowGamerXY** [comment]
Should have been fixed in the new 0.9 update.
